sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '0.12'
  - v4
  - stable
after_success:
  - 'travis-after-all && npm run semantic-release'
env:
  global:
    - secure: QBWeSKubwAEdeYBshn6BfCarck2S8tC0swWtZYXmkApe8k1aQGpTpHRZFHFRHpAsNrCyhbJ1k4RSuB9kCE/TSDAPXaREkUSbvCcCEjR1qZp+onF6Mb2touwFqaVTyBEndPVWX7U4qq48QkQfMOF/WJFPHQgTuYUGwrfzDlm2RhuZ4fvjbUkCMR+ETc75A41zOujxDMUPa/Bo0JMiaVhGqzQ7yi1V8RmwxBuYciEmM5UrJqLizhVVge8hADW1PlqrMZOAys1qXeVV9uAIW+yE2cxH/FJR7iOqGHyIuLJrKMWFY5664a1cTeskZrKqiymj16yEGTDrfhP5LjBJynyhsAo29fhLZR8S7hL0oAI6Hqc/hfIFZx3wLk8wdzbpSfUmcqKqkj9Wcjsnh1xjQ+16AbIgxd5Pfe3rmPJY3A5nka/Rq88ACNMb2GHFTj/0ExxmqIh8gR4a870YHczhVIR6ZqGalhAang3q5qt3BydzHycPoKQU44P1AF32/1qBDlwg/QvRgQrCylAMGmcQcC8eBMVDtvYkVZPoNmPu4PQ3hjnoUKPjTn41O3+yrAzLTVwaiEXLEKkf0FJIdTsIRFepIpWhS2vJtHfr0Jiuu2VzQnsa0xweVUtBDPXsvdFglP0SO1fomAx8PsCCK6C5iwDU/jTo+IhaH7R6jyh7MHVb8XI=
    - secure: H9c5MTDRxK7XpOZErt96YEIoXwaM4cKLIrtNq1vXjwpWfxW3na1+wy3lMfV4NQ/sC7DaQ2kBMXNhsYwnyHNmwZCIudxmvGp90fSE7BQoTaWO7ZokUBpfpB9WIM/NuRT1VtvbgbYetkJB/ViV0vNf+ShCQFZ5z8J/rBIwgDU+qGiOPTR/QBdAM/XP6zS2kXlolc1+lhmAB5wh9IQe+EUYDHspd9uDgelvhmmzUsJ/9donCh95ybkpgbSwc25SWQt15p0DYs/JF9N2R/fL+uG/fBB4GxOJOKZlM7RdaAXw1Hk1mO+Xnv4dnU9kl2nq1/wxCMa2KO9Dy1AwV3GCeRA3vNDkjOfiv0WwDQ4ygVBgg4twWNyIEvVCVbIkaUrt3Ex+gu5SccqffaRysYMKPu7QvlCGQhg/m0aJ04uZNManuHe6FpaBEnRI6KZk//1B2rA88dxyHlE6UA0uLrlXnOUlrpJLV5/5R5uyIpUN1qJKN6I+0LZsYByDxWaCro/hJOkZl7etmaGvRUZSBm/y5LQP3rnrqgAsKMrHR0a0gFLFRl63zSTtzrewbdO8RBcoOe1RzMAEvxswmTg68hvwDlEJNXiOisQvZySrpaZZH3BonmNTM9b8rLSk0P8d4cSMNyraDMSr+F4HxvQ4wUa+5muVJcyfC3MR4WVrYyyt4Et8GYs=
